spring.application.name: wuxiaworldhelper

# logger, to see logback-spring.xml
logging.level: INFO
logging.level.app: DEBUG

root.path: /Volumes/web/github.io/inkeast.com/
posts.source.path: ${root.path}posts_source/
docs.path: ${root.path}docs/